config/routes.rb
PartnerDashboard::Application.routes.draw do

  root :to => "home#index"


  match "/invite_requests/new", to: "invite_requests#new", via: :get, as: :new_invite_request
  #TODO: I don't want this send invite path to be public
  match "/invite_requests", to: "invite_requests#create", via: :post, as: :invite_requests
  match "/dashboard", to: "dashboard#dash", via: :get, as: :dashboard
  match "/dashboard/courses", to: "dashboard#courses", via: :get, as: :dashboard_courses
  match "/dashboard/students", to: "dashboard#students", via: :get, as: :dashboard_students
  #TODO:
  match "/relationships(.:format)", to: "relationships#create", via: :post, as: :relationships

  resources :students, only: [:index, :show, :edit, :update]
  resources :courses, only: [:index, :show]
  resources :partners, only: [:index, :show, :edit, :update]
  resources :professionals, only: [:show, :edit, :update]

  namespace :admin do
    root :to => "base#index"
    #resources :partners, only: :index
    resources :professionals, only: :index
    resources :students, only: :index
    resources :relationships, except: [:show, :edit]
   end

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}, :skip => [:invitations, :registrations]

  # only allow editing registrations, not creating them
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  #TODO, maybe you can yank some of the admin specific routes in here and put them above in the admin namespace block?
  devise_scope :user do
    get "/users/invitation/accept(.:format)" => "devise/invitations#edit", :as => "accept_user_invitation"
    put "admin/users/invitation(.:format)" => "admin/invitations#update"
    get "/users/invitation/remove(.:format)" => "admin/invitations#destroy", :as => "remove_user_invitation"
    post "admin/users/invitation(.:format)" => "admin/invitations#create", :as => "user_invitation"
    get "admin/users/invitation/new(.:format)" => "admin/invitations#new", :as => "new_user_invitation"
    get "admin/users/invitation/new_partner" => "admin/invitations#new_partner"
    post "admin/users/invitation/create_partner" => "admin/invitations#create_partner"
    get "admin/users/invitation/new_professional" => "admin/invitations#new_professional"
    post "admin/users/invitation/create_professional" => "admin/invitations#create_professional"
  end
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  attr_accessible :kind, :name, :professionals_attributes, :employments_attributes,
    :size, :website, :technologies, :about

  has_many :users

  has_many :students, :through => :relationships, source: :user
  has_many :relationships

  # accepts_nested_attributes_for :user, :employments

  validates :name, :kind, :website, presence: true
  validates :name, uniqueness: true
end

app/controllers/admin/partners_controller.rb
class Admin::PartnersController < Admin::BaseController
  def index
    @partners = Partner.all
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_filter :find_partner, only: [:show, :edit, :update]

  def index
    @partners = Partner.all
  end

  def show
    @professionals = @partner.users
  end

  def edit
    @professionals = @partner.users
  end

  def update
    if @partner.update_attributes(params[:partner])
      flash[:notice] = "Information has been updated."
      redirect_to @partner
    else
      flash[:alert] = "Information has not been updated."
      render action: "edit"
    end
  end

private
  def find_partner
    @partner = Partner.find(params[:id])
  end
end

app/views/partners/_form.html.erb
<%= form_for @partner, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :kind, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :kind, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :size, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :size, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :website, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :website, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :technologies, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :technologies, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :about, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :about, :class => 'text_field' %>
    </div>
  </div>



  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                partners_path, :class => 'btn' %>
  </div>
<% end %>

app/views/partners/edit.html.erb
<%- model_class = Partner -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/partners/index.html.erb
<div class="row-fluid">
  <h1>Code Fellows Partners</h1>
</div>

<div class="row-fluid">
  <% if @partners.empty? %>
  Sorry, there aren't any partners here yet...
  <% else %>
  <table id = "partners" class="table index">
    <thead>
      <tr>
        <th class="input-prepend">
          <span class="add-on"><i class="icon-filter"></i></span>
          <input id="partner-filter" type="text" class="search input-medium" placeholder="Filter Partners" />
        </th>
      </tr>
      <tr>
        <th class="sort" data-sort="name">Partner Name</th>
        <th>Partner Type</th>
      </tr>
    </thead>
    <tbody class="list">
      <% @partners.each do |partner| %>
        <tr>
          <td class="name"><%= link_to partner.name, partner_path(partner) %></td>
          <td class="kind"><%= partner.kind %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
</div>

<script>
  var options ={
    valueNames: ['name', 'kind']
  };

  var partnersList = new List('partners', options);
</script>

app/views/partners/new.html.erb
<%- model_class = Partner -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/partners/show.html.erb
<div class="row-fluid">
  <div class="span8">
    <h2>
      <%= @partner.name %>
    </h2>
    <table class="profile_contact_info">
      <tr>
        <th scope="row" style="text-align: left">Size</th>
        <td><%= @partner.size %></td>
      </tr>
      <tr>
        <th scope="row" style="text-align: left">Website</th>
        <td><%= link_to(@partner.website, @partner.website) %></td>
      </tr>
    </table>
  </div>
</div>

<div class="row-fluid">
  <div class="span8">
    <h3>Technologies</h3>
    <p>
    <% if @partner.technologies.nil? || @partner.technologies.empty? %>
      None provided....
    <% else %>
      <%= @partner.technologies %>
    <% end -%>
    </p>
    <% unless (@partner.about.nil? || @partner.about.empty?) %>
    <h3>About</h3>
    <p>
      <%= @partner.about %>
    </p>
    <% end %>
  </div>
</div>

<div class="row-fluid">
  <% if (current_user.has_role? :admin) || (current_user.has_role? :partner) %>
    <%= link_to "Edit Profile", edit_partner_path(@partner), class: "btn btn-primary" %>
  <% end %>
</div>

<div class="actions">
<%  if current_user.has_role? :student %>
  <% if current_user.connected? @partner %>
    <button class='btn btn-success btn-disabled' id='connect_button_partner[#{@partner.id}]'>Connected</button>
  <% elsif current_user.requested_connection? @partner %>
    <button class='btn disabled' id='connect_button_partner[#{@partner.id}]'>Pending</button>
  <%else%>
    <%= button_to("Connect",
           { controller: "relationships", action: "create", partner_id: @partner.id },
           remote: true, class: "btn btn-primary", id: "connect_button_partner[#{@partner.id}]") %>
  <% end %>
<%end %>
</div>

<div class="row-fluid">
  <div class="span8">
  <% if @professionals.empty? %>
  Sorry, there aren't any contacts here yet...
  <% else %>
  <table id = "partners" class="table index">
    <thead>
      <tr>
        <th class="input-prepend">
          <span class="add-on"><i class="icon-filter"></i></span>
          <input id="partner-filter" type="text" class="search input-medium" placeholder="Filter Partners" />
        </th>
      </tr>
      <tr>
        <th class="sort" data-sort="name">Professional Name</th>
      </tr>
    </thead>
    <tbody class="list">
      <% @professionals.each do |professional| %>
        <tr>
          <td class="name"><%= link_to professional.profile.name, professional_path(professional) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
  </div>
</div>

<script>
  var options ={
    valueNames: ['name', 'kind']
  };

  var partnersList = new List('partners', options);
</script>