config/routes.rb
PartnerDashboard::Application.routes.draw do

  root :to => "home#index"


  match "/invite_requests/new", to: "invite_requests#new", via: :get, as: :new_invite_request
  #TODO: I don't want this send invite path to be public
  match "/invite_requests", to: "invite_requests#create", via: :post, as: :invite_requests
  match "/dashboard", to: "dashboard#dash", via: :get, as: :dashboard
  match "/dashboard/courses", to: "dashboard#courses", via: :get, as: :dashboard_courses
  match "/dashboard/students", to: "dashboard#students", via: :get, as: :dashboard_students
  #TODO:
  match "/relationships(.:format)", to: "relationships#create", via: :post, as: :relationships

  resources :students, only: [:index, :show, :edit, :update]
  resources :courses, only: [:index, :show]
  resources :partners, only: [:index, :show, :edit, :update]
  resources :professionals, only: [:show, :edit, :update]

  namespace :admin do
    root :to => "base#index"
    #resources :partners, only: :index
    resources :professionals, only: :index
    resources :students, only: :index
    resources :relationships, except: [:show, :edit]
   end

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}, :skip => [:invitations, :registrations]

  # only allow editing registrations, not creating them
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  #TODO, maybe you can yank some of the admin specific routes in here and put them above in the admin namespace block?
  devise_scope :user do
    get "/users/invitation/accept(.:format)" => "devise/invitations#edit", :as => "accept_user_invitation"
    put "admin/users/invitation(.:format)" => "admin/invitations#update"
    get "/users/invitation/remove(.:format)" => "admin/invitations#destroy", :as => "remove_user_invitation"
    post "admin/users/invitation(.:format)" => "admin/invitations#create", :as => "user_invitation"
    get "admin/users/invitation/new(.:format)" => "admin/invitations#new", :as => "new_user_invitation"
    get "admin/users/invitation/new_partner" => "admin/invitations#new_partner"
    post "admin/users/invitation/create_partner" => "admin/invitations#create_partner"
    get "admin/users/invitation/new_professional" => "admin/invitations#new_professional"
    post "admin/users/invitation/create_professional" => "admin/invitations#create_professional"
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :partner
  belongs_to :user

  attr_accessible :connection_allowed, :partner_id, :user_id
  validates_uniqueness_of :partner_id, scope: :user_id

  #Make a pending relationship between a partner and user
  def self.pending(partner_id, student_id)
    new(partner_id: partner_id,
        user_id: student_id,
        connection_allowed: false)
  end

  def self.pending!(partner_id, student_id)
    pending(partner_id, student_id).save
  end

  def self.pending?
    !connection_allowed
  end

  #Make a connected relationship between a partner and user
  def self.connection_allowed(partner_id, student_id)
    new(partner_id: partner_id,
        user_id: student_id,
        connection_allowed: true)
  end

  def self.connection_allowed!(partner_id, student_id)
    connection_allowed(partner_id, student_id).save
  end

end

app/controllers/admin/relationships_controller.rb
class Admin::RelationshipsController < Admin::BaseController
  def index
    @relationships = Relationship.order("connection_allowed ASC")
  end

  def new
  end

  def create
  end

  def update
    #Get Relationship
    @relationship = Relationship.find(params[:id])
    @relationship.update_attribute(:connection_allowed, true)
  end

  def destroy
    @relationship = Relationship.find(params[:id])
    @relationship.destroy

    respond_to do |format|
      format.html { redirect_to action: :index }
      format.json { head :no_content }
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_filter :authenticate_user!

  #TODO: Use ajax?
  #TODO: Add conditional to make sure a connection be requested twice
  def create
    if current_user.has_role? :professional
      Relationship.pending!(current_user.partner.id, params[:user_id])
      respond_to do |format|
        format.html {
          redirect_to students_path
        }
        format.js {
          render 'create_student'
        }
      end
    else
      #is student
      Relationship.pending!(params[:partner_id], current_user.id)
      respond_to do |format|
        format.html {
          redirect_to partner_path(Partner.find(params[:partner_id]))
        }
        format.js {
          render 'create_partner'
        }
      end
    end
  end

  #TODO: Add destroy relationship
end

app/views/admin/relationships/_relationship.html.erb
<tr id="relationship[<%= relationship.id %>]">
  <% connection_allowed = relationship.connection_allowed? %>
  <td class="status_label"><%= render "status", locals: {connection_allowed: connection_allowed} %></td>
  <td><%= link_to relationship.partner.name, partner_path(relationship.partner) %></td>
  <td><%= link_to relationship.user.profile.name, student_path(relationship.user)  %></td>
  <% if relationship.connection_allowed? %>
    <td><%= link_to "Destroy", admin_relationship_path(relationship),
              method: "delete",
              data: {
                confirm: "Are you sure?"
              },
              class: "btn btn-primary" %></td>
  <% else %>
    <td><%= link_to "Connect", admin_relationship_path(relationship),
              method: "put",
              remote: true,
              class: "btn btn-primary" %>
        <%= link_to "Destroy", admin_relationship_path(relationship),
              method: "delete",
              data: {
                confirm: "Are you sure?"
              },
              class: "btn btn-primary" %></td>
  <% end %>
</tr>

app/views/admin/relationships/_status.html.erb
<% if locals[:connection_allowed] %>
  <span class="label label-success">Connected</span>
<% else %>
  <span class="label label-warning">Pending</span>
<% end %>

app/views/admin/relationships/index.html.erb
<div class="row-fluid">
  <h1>Manage Connections</h1>
</div>

<div class="row-fluid">
  <table id="relationships" class="table">
    <thead>
      <tr>
        <th>Status</th>
        <th>Partner</th>
        <th>Student</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <%= render @relationships %>
    </tbody>
  </table>
</div>

<script>

</script>