config/routes.rb
PartnerDashboard::Application.routes.draw do

  root :to => "home#index"


  match "/invite_requests/new", to: "invite_requests#new", via: :get, as: :new_invite_request
  #TODO: I don't want this send invite path to be public
  match "/invite_requests", to: "invite_requests#create", via: :post, as: :invite_requests
  match "/dashboard", to: "dashboard#dash", via: :get, as: :dashboard
  match "/dashboard/courses", to: "dashboard#courses", via: :get, as: :dashboard_courses
  match "/dashboard/students", to: "dashboard#students", via: :get, as: :dashboard_students
  #TODO:
  match "/relationships(.:format)", to: "relationships#create", via: :post, as: :relationships

  resources :students, only: [:index, :show, :edit, :update]
  resources :courses, only: [:index, :show]
  resources :partners, only: [:index, :show, :edit, :update]
  resources :professionals, only: [:show, :edit, :update]

  namespace :admin do
    root :to => "base#index"
    #resources :partners, only: :index
    resources :professionals, only: :index
    resources :students, only: :index
    resources :relationships, except: [:show, :edit]
   end

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}, :skip => [:invitations, :registrations]

  # only allow editing registrations, not creating them
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  #TODO, maybe you can yank some of the admin specific routes in here and put them above in the admin namespace block?
  devise_scope :user do
    get "/users/invitation/accept(.:format)" => "devise/invitations#edit", :as => "accept_user_invitation"
    put "admin/users/invitation(.:format)" => "admin/invitations#update"
    get "/users/invitation/remove(.:format)" => "admin/invitations#destroy", :as => "remove_user_invitation"
    post "admin/users/invitation(.:format)" => "admin/invitations#create", :as => "user_invitation"
    get "admin/users/invitation/new(.:format)" => "admin/invitations#new", :as => "new_user_invitation"
    get "admin/users/invitation/new_partner" => "admin/invitations#new_partner"
    post "admin/users/invitation/create_partner" => "admin/invitations#create_partner"
    get "admin/users/invitation/new_professional" => "admin/invitations#new_professional"
    post "admin/users/invitation/create_professional" => "admin/invitations#create_professional"
  end
end

app/controllers/admin/invitations_controller.rb
class Admin::InvitationsController < Devise::InvitationsController
  def new
    if params[:invite_request]
      @invite_request = InviteRequest.new params[:invite_request]
      user_params = ActiveSupport::HashWithIndifferentAccess.new(
        email: @invite_request.email,
        partner_id: nil
        )
      if Partner.exists?(name: @invite_request.company)
        user_params.merge! partner_id: Partner.find_by_name(@invite_request.company).id
      end
      build_resource user_params
    else
      build_resource
    end
  end

  def create
    # record whether or not user should be admin, but remove from params for now
    make_admin = if resource_params.delete(:admin) == "1"
      # TODO: actually use validations for this
      resource_params.delete(:partner_id)
      true
    else
      false
    end

    super
    # actually save user as admin
    resource.update_attribute(:admin, true) if make_admin
  end

  def new_partner
    if params[:partner_name]
      @partner = Partner.new(name: params[:partner_name])
    else
      @partner = Partner.new()
    end
  end

  def create_partner
    @partner = Partner.new(params[:partner])
    if @partner.save
      render "create_partner"
    else
      render "new_partner"
    end
  end

  def new_professional
    #TODO, testing if there are params in the URL, there needs to be a cleaner way.
    if get_referer_params("invite_request[first_name]")
      #TODO, add phone number to invite request and new professional form
 #     @professional = User.new(name: get_referer_params("invite_request[first_name]").capitalize + " " +
  #                                                       get_referer_params("invite_request[last_name]").capitalize,
   #                                    email: get_referer_params("invite_request[email]"))
      @professional = User.new(email: get_referer_params("invite_request[email]"))
      @professional.employments.build(title: get_referer_params("invite_request[role]"),
                                      partner_id: params[:partner_id])
    else
      @professional = User.new(email: params[:email])
      @professional.employments.build(partner_id: params[:partner_id])
    end
  end

  def create_professional
    @professional = User.new(params[:professional])
    if @professional.save
      @professional.add_role :professional
      @professional.employments.build(partner_id: params[:partner_id], title: get_referer_params("invite_request[role]"))
      render "create_professional"
    else
      render "new_professional"
    end
  end

end

app/views/admin/invitations/_new_partner_form.html.erb
<h2>Create Partner</h2>
<%= form_for @partner, url: admin_users_invitation_create_partner_path, remote: true do |f| %>

  <% if @partner.errors.any? %>
    <div id="error_explanation" class="alert">
      <h3><%= pluralize(@partner.errors.count, "error") %>
        prohibited this partner from being saved:</h3>
      <ul>
      <% @partner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name, "Company Name" %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :kind, "Type of Company (Startup, Agency, etc.)" %>
    <%= f.text_field :kind %>
  </p>

  <p>
    <%= f.label :website %>
    <%= f.text_field :website %>
  </p>

  <p>
    <%= f.submit "Create Partner", class: "btn btn-primary" %>
  </p>
<% end %>

<button id="go_back_button" class="btn btn-primary">Go Back</button>

app/views/admin/invitations/_new_professional_form.html.erb
<h2>Add <%= @professional.name %></h2>
<%= form_for @professional, url: admin_users_invitation_create_professional_path, remote: true do |f| %>
  <% if @professional.errors.any? %>
    <div id="error_explanation" class="alert">
      <h3><%= pluralize(@professional.errors.count, "error") %>
        prohibited this user from being saved:</h3>
      <ul>
      <% @professional.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :email %>
  <%= f.label :name  %>
  <%= f.text_field :name  %>
  <%= f.fields_for :employments do |builder| %>
      <%= builder.label :role  %>
      <%= builder.text_field :role  %>
      <%= builder.hidden_field :partner_id %>
  <% end %>

  <p>
    <%= f.submit "Add User", class: "btn btn-primary" %>
  </p>
<% end %>

<button id="go_back_button" class="btn btn-primary">Go Back</button>

app/views/admin/invitations/_select_partner_form.html.erb
<%= fields_for resource do |f| %>
  <%= f.label "Assign to Partner"%>
  <%= f.collection_select :partner_id, Partner.order("name ASC"), :id, :name, :prompt => "Select A Partner" -%>
<% end %>

app/views/admin/invitations/new.html.erb
<div class="row-fluid">
  <% if @invite_request %>
    <h2>Invitee Info</h2>
    <ul>
      <% @invite_request.instance_values.each do |key, value| %>
        <li><%= key.to_s.delete(":").capitalize  %>: <%= value %></li>
      <% end %>
    </ul>
  <% end %>

  <div id="form_container">
    <div id="invitation_form">
      <h2><%= t "devise.invitations.new.header" %></h2>
      <%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:method => :post} do |f| %>
        <%= devise_error_messages! %>

        <% resource.class.invite_key_fields.each do |field| -%>
          <%= f.label field %>
          <%= f.text_field field, value: resource.email  %>
        <% end %>

        <%= f.check_box :admin %> Admin

        <div id="partner-controls">
          <%= render "select_partner_form" %>

          <% if @invite_request %>
            <span id="add_partner_link">
              <%= link_to "Partner not listed?", {
                controller: "invitations",
                action: "new_partner",
                partner_name: @invite_request.company,
                remote: true }%>
            </span>
          <% else %>
            <span id="add_partner_link">
              <%= link_to "Partner not listed?", {
                controller: "invitations",
                action: "new_partner",
                remote: true }%>
            </span>
          <% end %>
        </div>

        <div id="add_professional_button" style ="display:none">
          <button class="btn btn-primary">Add as Professional</button>
        </div>

        </br>

        <div class="controls">
          <%= f.submit t("devise.invitations.new.submit_button"), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
    <div id="new_partner_form"></div>
    <div id="new_professional_form"></div>
  </div>

</div>

<script>
  $(document).ready( function(){
    if ($("#user_partner_id option:selected").text() != "Select A Partner") {
      $("#add_professional_button").show()
    }
    else {
      $("#add_professional_button").hide()
    }

    //Assign click handler to partner dropdown
    $("#user_partner_id").change( function(e){
      if ($("#user_partner_id option:selected").text() != "Select A Partner") {
        $("#add_professional_button").fadeIn()
      }
      else {
        $("#add_professional_button").fadeOut()
      }
    });

    $("#add_professional_button").click( function(e){
      var data = {
        partner_id: $("#user_partner_id option:selected").val(),
        email: $("#user_email").val()
      }
      $.ajax({
        url: "/admin/users/invitation/new_professional",
        data: data,
        dataType: "script"
      });

      return false;
    });

    // don't show partner select when user is admin
    $('#user_admin').on('click', function(event){
      if ($(this).is(':checked')) {
        $('#partner-controls').hide();
      } else {
        $('#partner-controls').show();
      }
    });
  });
</script>