config/routes.rb
PartnerDashboard::Application.routes.draw do

  root :to => "home#index"


  match "/invite_requests/new", to: "invite_requests#new", via: :get, as: :new_invite_request
  #TODO: I don't want this send invite path to be public
  match "/invite_requests", to: "invite_requests#create", via: :post, as: :invite_requests
  match "/dashboard", to: "dashboard#dash", via: :get, as: :dashboard
  match "/dashboard/courses", to: "dashboard#courses", via: :get, as: :dashboard_courses
  match "/dashboard/students", to: "dashboard#students", via: :get, as: :dashboard_students
  #TODO:
  match "/relationships(.:format)", to: "relationships#create", via: :post, as: :relationships

  resources :students, only: [:index, :show, :edit, :update]
  resources :courses, only: [:index, :show]
  resources :partners, only: [:index, :show, :edit, :update]
  resources :professionals, only: [:show, :edit, :update]

  namespace :admin do
    root :to => "base#index"
    #resources :partners, only: :index
    resources :professionals, only: :index
    resources :students, only: :index
    resources :relationships, except: [:show, :edit]
   end

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}, :skip => [:invitations, :registrations]

  # only allow editing registrations, not creating them
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  #TODO, maybe you can yank some of the admin specific routes in here and put them above in the admin namespace block?
  devise_scope :user do
    get "/users/invitation/accept(.:format)" => "devise/invitations#edit", :as => "accept_user_invitation"
    put "admin/users/invitation(.:format)" => "admin/invitations#update"
    get "/users/invitation/remove(.:format)" => "admin/invitations#destroy", :as => "remove_user_invitation"
    post "admin/users/invitation(.:format)" => "admin/invitations#create", :as => "user_invitation"
    get "admin/users/invitation/new(.:format)" => "admin/invitations#new", :as => "new_user_invitation"
    get "admin/users/invitation/new_partner" => "admin/invitations#new_partner"
    post "admin/users/invitation/create_partner" => "admin/invitations#create_partner"
    get "admin/users/invitation/new_professional" => "admin/invitations#new_professional"
    post "admin/users/invitation/create_professional" => "admin/invitations#create_professional"
  end
end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
  <a href="https://www.codefellows.org"><%= image_tag "cf_logo.png", id: "corner_logo" %></a>
  <% if user_signed_in? %>
    <%= render 'layouts/navbar_account' %>
  <% end %>
  <div class="navbar-inner">
    <div class="container">
    <ul class="nav">
    <%= link_to "Partner Dashboard", root_path, class: "brand" %>
    <% if user_signed_in? %>
      <% if current_user.has_role? :admin %>
        <%= render 'layouts/navbar_admin_links' %>
      <% else %>
        <%= render 'layouts/navbar_links' %>
      <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navbar_account.html.erb
<ul class="nav pull-right">
  <li class="dropdown">
    <a href="javascript:false;" class="dropdown-toggle" data-toggle="dropdown">
      Account
      <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to "Edit account", edit_user_registration_path %></li>
      <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "btn-btn-navbar" %></li>
    </ul>
  </li>
</ul>

app/views/layouts/_navbar_admin_links.html.erb
<li class="dropdown">
  <a class="dropdown-toggle" id="adminLabel" role="button" data-toggle="dropdown" href="#">
    Admin
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu" role="menu" aria-labelledby="adminLabel">
    <li>
      <%= link_to "Invite A New User", new_user_invitation_path, :class => "btn-btn-navbar" %>
    </li>
    <li>
      <%= link_to "Manage Connections", admin_relationships_path, :class => "btn-btn-navbar" %>
    <li>
  </ul>
</li>

<li><%= link_to "Partners", partners_path, :class => "btn-btn-navbar" %></li>
<li><%= link_to "Professionals", admin_professionals_path, :class => "btn-btn-navbar" %></li>

<li><%= link_to "Courses", courses_path, :class => "btn-btn-navbar" %></li>
<li><%= link_to "Students", students_path, :class => "btn-btn-navbar" %></li>

app/views/layouts/_navbar_links.html.erb
<li><%= link_to "Courses", courses_path, :class => "btn-btn-navbar" %></li>
<% if current_user.has_role? :professional %>
  <li><%= link_to "Students", students_path, :class => "btn-btn-navbar" %></li>
  <li><%= link_to "My Company", partner_path(current_user.partner) %></li>
<% end %>
<% if current_user.has_role? :student %>
  <li><%= link_to "Partners", partners_path, :class => "btn-btn-navbar" %></li>
  <li><%= link_to "My Profile", student_path(current_user) %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Partner Dashboard</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
  <div id="wide_background">
    <div class="base container">
      <% flash.each do |key, value| %>
        <div class="alert <%= key == :alert ? "alert-error" : "alert-info" %>">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= value %>
        </div>
      <% end %>
      <div class="container"><%= yield %></div>
    </div>
  </div>
</body>
</html>